//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestProveedores.NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webservice_cpEntities : DbContext
    {
        public webservice_cpEntities()
            : base("name=webservice_cpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<localidad> localidads { get; set; }
        public virtual DbSet<municipio> municipios { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
    }
}
